development:
  adapter: postgresql
  encoding: unicode
  database: dothistory_dev
  pool: 5
  username: dothistory
  password: dothistory

test:
  adapter: postgresql
  encoding: unicode
  database: dothistory_test
  pool: 5
  username: dothistory
  password: dothistory

